main/urls.py
from django.urls import path
from .views import *

app_name = 'main'

urlpatterns = [
    path('home/', home_view, name='home'),
    path('contact/', contact_view, name='contact'),
    path('about/', about_view, name='about'),
    path('course/', coures_view, name='course'),
    path('courses/<int:course_id>/', course_detail_view, name='course_detail'),
]

ssti_site/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import home_view

urlpatterns = [
    path('', home_view),
    path('main/', include('main.urls')),
    path('account/', include('account.urls')),
    path('instructor/', include('instructor.urls')),
    path('student/', include('student.urls')),
    path("admin/", admin.site.urls),
]

student/urls.py
from django.urls import path
from .views import *

app_name = 'student'

urlpatterns = [
    path('home/', home_view, name='home'),
    path('course/', course_list, name='course'),
    path('profile/', student_profile, name='student_profile'),
    path('edit_profile', edit_profile, name='edit_profile'),
    path('course/<str:course_id>/', course_detail, name='course_detail'),
    path('enroll/<int:course_id>/', enroll_course, name='enroll_course'),
    path('course/<int:course_id>/feedback/', submit_feedback, name='submit_feedback'),
    path('course/<int:course_id>/request-certificate/', certificate_request, name='request_certificate'),
    path('certificate/<int:cert_id>/download/', download_certificate, name='download_certificate'),
    path('wishlist/', wishlist, name='wishlist'),
    path('wishlist/add/<int:course_id>/', add_to_wishlist, name='add_to_wishlist'),
    path('wishlist/remove/<int:course_id>/', remove_from_wishlist, name='remove_from_wishlist'),
    path('favorites/add/<int:course_id>/', add_to_favorites, name='add_to_favorites'),
    path('favorites/remove/<int:course_id>/', remove_from_favorites, name='remove_from_favorites'),
    path('favorites/', favorite_list, name='favorite_list'),
    path('submit-assessment/<int:assessment_id>/', submit_assessment, name='submit_assessment'),
    path('assessment-results/<int:attempt_id>/', assessment_results, name='assessment_results'),
]

student/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator, MaxValueValidator
from django.core.exceptions import ValidationError
import random
from django.conf import settings
from instructor.models import Instructor, Course, Video, CreateAssessment


user = get_user_model()

class Student(models.Model):
    first_name = models.CharField(max_length=120, blank=False, unique=False)
    last_name = models.CharField(max_length=120, blank=False, unique=False)
    student_id = models.CharField(max_length=8, blank=False, unique=True)
    date_of_birth = models.DateField()
    phone_number = models.CharField(max_length=10, blank=False, unique=True)

    def __str__(self) -> str:
        return f'Student Name: {self.first_name} {self.last_name}'
    
    def save(self, *args, **kwargs):
        if not self.student_id:
            self.student_id = self.generate_student_id()
        super().save(*args, **kwargs)

    def generate_student_id(self):
        while True:
            student_id = ''.join([str(random.randint(0, 9)) for _ in range(8)])
            if not Student.objects.filter(student_id=student_id).exists():
                return student_id


class StudentProfile(models.Model):
    student = models.OneToOneField(Student, on_delete=models.CASCADE, related_name='stdent')
    profile_picture = models.ImageField(upload_to='student profile')
    bio = models.TextField(max_length=500, blank=True, null=True)
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    address = models.CharField(max_length=255, blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    postal_code = models.CharField(max_length=10, blank=True, null=True)
    country = models.CharField(max_length=100, blank=True, null=True)
    date_of_birth = models.DateField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f'Student Name: {self.student.first_name} {self.student.last_name}'


class EnrollCourse(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='enroll_courses')
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='student')
    enroll_at = models.DateTimeField(auto_now_add=True)
    progress = models.DecimalField(max_digits=3, decimal_places=2, default=0)
    is_complete = models.BooleanField(default=False)
    
    def __str__(self) -> str:
        return f'Student: {self.student.first_name}'
    
    def complete_course(self):
        self.is_complete = True
        
        
class ViewCourse(models.Model):
    instructor = models.ForeignKey(Instructor, on_delete=models.CASCADE, related_name='instructor_profile')
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='view_course')
    course = models.ForeignKey(Video, on_delete=models.CASCADE, related_name='course_details')
    viewed_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f'Student: {self.student.first_name} {self.student.last_name} Course Name: {self.course.course_name} Instructor Name: {self.instructor.full_name}'


class Wishlist(models.Model):
    student = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='wishlist')
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='wishlist_course')
    added_at = models.DateField(auto_now_add=True)

    class Meta:
        unique_together = ('student', 'course')

    def __str__(self):
        return f"{self.student.username} - {self.course.title}"

class AttemptAssessment(models.Model):
    student = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='attempt_assessments')
    assessment = models.ForeignKey(CreateAssessment, on_delete=models.CASCADE, related_name='attempted_assessments')
    selected_answer = models.CharField(max_length=1, choices=CreateAssessment.CORRECT_ANSWER_OPTION, blank=True, null=True)
    is_correct = models.BooleanField(default=False)
    marks_obtained = models.PositiveIntegerField(default=0)

    def save(self, *args, **kwargs):
        # Automatically mark the assessment if it's an MCQ
        if self.assessment.question_type == 'MCQ':
            self.is_correct = self.selected_answer == self.assessment.correct_answer
            self.marks_obtained = self.assessment.marks if self.is_correct else 0
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.student.username} - {self.assessment.question_text}"



class TrackProgress(models.Model):
    student = models.ForeignKey(EnrollCourse, on_delete=models.CASCADE, related_name='track_progrss')
    progress_percentage = models.DecimalField(max_digits=3, decimal_places=2, default=0)
    
    
class Feedback(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='student_feedback')
    instructor = models.ForeignKey(Instructor, on_delete=models.CASCADE, related_name='instructor_feedback')
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='course_feedback')
    rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)], help_text='Rate from 1 to 5')
    feedback_text = models.TextField(blank=True, null=True)
    
    def __str__(self) -> str:
        return f'Feedback {self.student.first_name} {self.student.last_name}'

    
class CertificateRequest(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='certificates_request')
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='certificate_requests')
    request_date = models.DateTimeField(auto_now_add=True)
    certificate_file = models.FileField(upload_to='certificates/', null=True, blank=True)
    is_approved = models.BooleanField(default=False)
    approved_at = models.DateTimeField(blank=True, null=True)
    
    class Meta:
        unique_together = ('student', 'course')
        
    def __str__(self):
        return f"Certificate request by {self.student.username} for {self.course.title}"
    
    # Ensure the student has completed the course before requesting the certificate
    def clean(self):
        course_completion = ViewCourse.objects.filter(student=self.student, course=self.course, is_completed=True).exists()
        if not course_completion:
            raise ValidationError('You cannot request a certificate for a course you have not completed.')


class Favorite(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='favorites')
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='favorited_by')
    added_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f'Student Name: {self.student.first_name} {self.student.last_name} Favorite Course: {self.course.title}' 

student/forms.py
from .models import Feedback, StudentProfile, CertificateRequest
from django import forms


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['rating', 'feedback_text']
        
        widgets = {
            'rating': forms.RadioSelect(choices=[(i, str(i)) for i in range(1, 6)], attrs={'class': 'form-control'}),
            'feedback_text': forms.Textarea(attrs={'class': 'form-control', 'rows': 4}),
        }


class StudentProfileForm(forms.ModelForm):
    class Meta:
        model = StudentProfile
        fields = ['profile_picture', 'bio', 'phone_number', 'address', 'city', 'postal_code', 'country', 'date_of_birth']
        widgets = {
            'bio': forms.Textarea(attrs={'class': 'form-control', 'rows': 4}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
            'city': forms.TextInput(attrs={'class': 'form-control'}),
            'postal_code': forms.TextInput(attrs={'class': 'form-control'}),
            'country': forms.TextInput(attrs={'class': 'form-control'}),
            'date_of_birth': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
        }

class RequestCertificateForm(forms.ModelForm):
    class Meta:
        model = CertificateRequest
        fields = ['course']

        widgets = {
            'course': forms.Select(attrs={'class': 'form-control'}),
        }

student/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.contrib import messages
from django.http import HttpResponse
from io import BytesIO
from reportlab.pdfgen import canvas
from .forms import *
from .models import *
from instructor.models import Course, Video


def home_view(request):
    
    return render(request, 'student/index.html')

def student_profile(request):
    profile = StudentProfile.objects.get(student=request.user)
    
    if request.method == 'POST':
        form = StudentProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('profile_view')  # Redirect to the profile view page
    else:
        form = StudentProfileForm(instance=profile)
    
    return render(request, 'student/student_profile.html', {'form': form})

def edit_profile(request):
    return render(request, 'student/forms/edit_profile.html', )

def add_to_wishlist(request, course_id):
    course = get_object_or_404(Course, id=course_id)
    wishlist, created = Wishlist.objects.get_or_create(student = request.user, course=course)
    if created:
        return redirect('wishlist')
    else:
        return redirect('course_detail', course_id=course.id)
    
def remove_from_wishlist(request, course_id):
    course = get_object_or_404(Course, id=course_id)
    wishlist = Wishlist.objects.filter(student=request.user, course=course)
    if wishlist.exists():
        wishlist.delete()
    return redirect('wishlist')

def wishlist(request):
    wishlist = Wishlist.objects.filter(student=request.user).select_related('course')
    return render(request, 'wishlist/wishlist.html', {'wishlist': wishlist})

# Course to be displayed from the instructor or the admin
def course_list(request):
    courses = Course.objects.filter(status=True)

    return render(request, 'student/course.html', {'courses': courses})

# Details for the related course
def course_detail(request, course_id):
    courses = get_object_or_404(Course, id=course_id)

    videos = courses.video.all()

    context = {
        'courses': courses,
        'videos': videos
    }

    return render(request, 'student/course_detail.html', context)

def enroll_course(request, course_id):
    course = Course.objects.get(id=course_id)
    student = request.user.studentprofile
    
    if EnrollCourse.objects.filter(student=student, course=course).exists():
        messages.warning(request, 'You have already enrolled in this course')
    else:
        EnrollCourse.objects.create(student=student, course=course)
        messages.success(request, f'You have successfully enrolled in {course.title}')
        
    return redirect('course_detail', course=course_id)

def submit_assessment(request, assessment_id):
    assessment = get_object_or_404(CreateAssessment, id=assessment_id)
    
    if request.method == 'POST':
        selected_answer = request.POST.get('selected_answer')
        
        attempt = AttemptAssessment(
            student=request.user,
            assessment=assessment,
            selected_answer=selected_answer
        )
        attempt.save()
        return redirect('assessment_results', attempt_id=attempt.id)
    
    return render(request, 'student/submit_assessment.html', {'assessment': assessment})

def assessment_results(request, attempt_id):
    attempt = get_object_or_404(AttemptAssessment, id=attempt_id)
    return render(request, 'student/assessment_result.html', {'attempt': attempt})

def certificate_request(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    
    completed = ViewCourse.objects.filter(student=request.user, course=course, is_complete=True).exists()
    
    if not completed:
        messages.error(request, 'You cannot request a for a course you have not completed!')
        return redirect('course_detail', course_id=course_id)
    
    cert_request, created = CertificateRequest.objects.get_or_create(student=request.user, course=course)
    
    #Generate a certificate PDF
    if created:
        buffer = BytesIO()
        p = canvas.Canvas(buffer)
        p.drawString(100, 750, f'Certificate of Completion')
        p.drawString(100, 700, f"Congratulations {request.user.get_full_name()}!")
        p.drawString(100, 650, f"You have successfully completed the course: {course.title}.")
        p.showPage()
        p.save()
        
        # Save the PDF in the certificate request model
        cert_request.certificate_file.save(f"{request.user.username}_{course.title}_certificate.pdf", buffer)
        
    return redirect('download_certificate', cert_id=cert_request.id)

def certificate_status_view(request):
    student = request.user.student
    certificate_requests = CertificateRequest.objects.filter(student=student)

    return render(request, 'student/certificate_status.html', {'certificate_requests': certificate_requests})

def download_certificate(request, certificate_id):
    certificate_request = get_object_or_404(CertificateRequest, id=certificate_id, student=request.user.student)
    
    if certificate_request.is_approved and certificate_request.certificate_file:
        # Serve the certificate file for download
        response = HttpResponse(certificate_request.certificate_file, content_type='application/pdf')
        response['Content-Disposition'] = f'attachment; filename="{certificate_request.course.title}_certificate.pdf"'
        return response
    else:
        return redirect('certificate_status') 

def submit_feedback(request, course_id):
    course = Course.objects.get(id=course_id)
    instructor = course.instructor_profile
    student = request.user.student
    
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            feedback = form.save(commit=False)
            feedback.student = student
            feedback.instructo = instructor
            feedback.course = course
            feedback.save()
            messages.success(request, 'Feedback submitted successfully')
            return redirect('course_detail', course_id=course.id)
        
    else:
        form = FeedbackForm()
        
    return render(request, 'student/submit_feedback', {'form': form, 'course': course})

def add_to_favorites(request, course_id):
    course = get_object_or_404(Course, id=course_id)
    student = request.user.student
    favorite, created = Favorite.objects.get_or_create(student=student, course=course)
    return redirect('student:course_list')

def remove_from_favorites(request, course_id):
    course = get_object_or_404(Course, id=course_id)
    student = request.user.student
    favorite = Favorite.objects.filter(student=student, course=course).delete()
    return redirect('student:favorite_list')

def favorite_list(request):
    # student = request.user.student
    favorites = Favorite.objects.filter()
    return render(request, 'student/courses/favorite_list.html', {'favorites': favorites})

student/templates/student/base.html
{% load django_bootstrap5 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    {% bootstrap_css %}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'student/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'student/css/responsive.css' %}">

</head>
<body>

    <div class="all-navbar">
        <div class="navbar-container">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container justify-content-center">
                    <a class="navbar-brand" href="#">SSTI</a>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          Categories
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="#">SSTI Business</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                        </ul>
                    </li>
        
                    <div class="d-flex">
                        <form class="d-flex me-2">
                            <input class="form-control search-bar" type="search" placeholder="Search" aria-label="Search">
                        </form>
                    </div>
        
                    <div>
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0 text-center">
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="#">SSTI Business</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Teach on SSTI</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">My Learning</a>
                            </li>
                        </ul> 
                    </div>
        
                    <div class="d-flex justify-content-center align-items-center">
                        <a href="{% url 'student:favorite_list' %}" class="nav-link"><i class="fas fa-heart"></i></a>
                        <a href="#" class="nav-link"><i class="fas fa-shopping-cart"></i></a>
                        <a href="#" class="nav-link"><i class="fas fa-bell"></i></a>
        
                        <li class="nav-item dropdown profile-dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="profileDropdown" role="button">
                                {% if user.profile_picture %}
                                    <img src="{{ user.profile_picture.url }}" class="rounded-circle" alt="Profile Picture" style="width: 40px; height: 40px;">
                                {% else %}
                                    <i class="fas fa-user-circle fa-2x"></i>
                                {% endif %}
                            </a>
                            <ul class="dropdown-menu dropdown-menu-start" aria-labelledby="profileDropdown">
                                <li>
                                    <a class="dropdown-item">
                                        {% if user.profile_picture %}
                                            <img src="{{ user.profile_picture.url }}" class="rounded-circle" alt="Profile Picture" style="width: 40px; height: 40px;">
                                        {% else %}
                                            <i class="fas fa-user-circle fa-2x"></i>
                                        {% endif %}
                                        <div class="profile-info">
                                            <h6 class="mb-0">Emmanuel Aduah</h6>
                                            <p class="mb-0 text-muted">aduahimma18@gmail.com</p>
                                        </div>
                                    </a>
                                </li>
                                <hr>
                                <li><a class="dropdown-item" href="{% url 'student:student_profile' %}">My Profile</a></li>
                                <li><a class="dropdown-item" href="{% url 'student:edit_profile' %}">Edit Profile</a></li>
                                <li><a class="dropdown-item" href="#"></a></li>
                                <li><a class="dropdown-item" href=""></a></li>
                                <hr>
                                <li><a class="dropdown-item" href="#">My Cart</a></li>
                                <li><a class="dropdown-item" href="{% url 'student:wishlist' %}">Wishlist</a></li>
                                <li><a class="dropdown-item" href="#">Notifications</a></li>
                                <li><a class="dropdown-item" href="">Teach on SSTI</a></li>
                                <hr>
                                <li><a class="dropdown-item" href="#">Notifications</a></li>
                                <li><a class="dropdown-item" href="#">Messages</a></li>
                                <hr>
                                <li><a class="dropdown-item" href="#">Account Settings</a></li>
                                <li><a class="dropdown-item" href="#">Payment Method</a></li>
                                <li><a class="dropdown-item" href="#">Purchase History</a></li>
                                <li><a class="dropdown-item" href="#">Subscriptions</a></li>
                                <hr>
                                <li><a class="dropdown-item" href="#">Edit Profile</a></li>
                                <li><a class="dropdown-item" href="#">Help and Support</a></li>
                                <li><a class="dropdown-item" href="#">Language</a></li>
                                <hr>
                                <li><a class="dropdown-item" href="#">Log Out</a></li>
                            </ul>
                        </li>                        
                </div>
            </nav>
        </div>        
             
        <div>      
            <nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm py-3">
                <div class="container">
                    <!-- Toggler button for mobile view -->
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" 
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
        
                    <!-- Navbar Links -->
                    <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
                        <ul class="navbar-nav">
                            <!-- All Courses Link -->
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'student:course' %}">All Courses</a>
                            </li>
        
                            <!-- Features Link -->
                            <li class="nav-item">
                                <a class="nav-link" href="#">Enrolled Courses</a>
                            </li>
        
                            <!-- Pricing Link -->
                            <li class="nav-item">
                                <a class="nav-link" href="#">My Certificate</a>
                            </li>
        
                            <!-- Dropdown for All Courses -->
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Categories
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" href="#">SSTI Business</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" href="#">Something else here</a></li>
                                </ul>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Assignment</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
    </div>

    <div class="container-fluid">
        {% block content %}
        {% endblock %}
    </div>

    {% bootstrap_javascript %}
</body>
</html>