account/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views

app_name = 'account'

urlpatterns = [
    path('signup/', signup_view, name='signup'),
    path('login/', login_view, name='login'),
    path('logout/', logout, name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),
]

main/urls.py
from django.urls import path
from .views import *

app_name = 'main'

urlpatterns = [
    path('home/', home_view, name='home'),
    path('contact/', contact_view, name='contact'),
    path('about/', about_view, name='about'),
    path('course/', coures_view, name='course'),
    path('courses/<int:course_id>/', course_detail_view, name='course_detail'),
]

ssti_site/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import home_view

urlpatterns = [
    path('', home_view),
    path('main/', include('main.urls')),
    path('account/', include('account.urls')),
    path('instructor/', include('instructor.urls')),
    path('student/', include('student.urls')),
    path("admin/", admin.site.urls),
]

student/urls.py
from django.urls import path
from .views import *

app_name = 'student'

urlpatterns = [
    path('home/', home_view, name='home'),
    path('course/', course_list, name='course'),
    path('profile/', student_profile, name='student_profile'),
    path('edit_profile', edit_profile, name='edit_profile'),
    path('course/<str:course_id>/', course_detail, name='course_detail'),
    path('enroll/<int:course_id>/', enroll_course, name='enroll_course'),
    path('course/<int:course_id>/feedback/', submit_feedback, name='submit_feedback'),
    path('course/<int:course_id>/request-certificate/', certificate_request, name='request_certificate'),
    path('certificate/<int:cert_id>/download/', download_certificate, name='download_certificate'),
    path('wishlist/', wishlist, name='wishlist'),
    path('wishlist/add/<int:course_id>/', add_to_wishlist, name='add_to_wishlist'),
    path('wishlist/remove/<int:course_id>/', remove_from_wishlist, name='remove_from_wishlist'),
    path('favorites/add/<int:course_id>/', add_to_favorites, name='add_to_favorites'),
    path('favorites/remove/<int:course_id>/', remove_from_favorites, name='remove_from_favorites'),
    path('favorites/', favorite_list, name='favorite_list'),
    path('submit-assessment/<int:assessment_id>/', submit_assessment, name='submit_assessment'),
    path('assessment-results/<int:attempt_id>/', assessment_results, name='assessment_results'),
]

main/models.py
from django.db import models

class Address(models.Model):
    street_address = models.CharField(max_length=122, unique=True, null=False)
    phone_number = models.CharField(max_length=15, null=False, unique=True)
    email_address = models.EmailField()


class SociolMedia(models.Model):
    facebook_address = models.URLField()
    twitter_address = models.URLField()
    youtube_address = models.URLField()
    linkedin_address = models.URLField()
    instagram_address = models.URLField()


class Courses(models.Model):
    course_name = models.CharField(max_length=128, unique=True, null=False)
    image_file = models.ImageField(upload_to='course images')
    short_content = models.CharField(max_length=255, null=False, unique=True)
    main_content = models.CharField(max_length=2500, blank=True, unique=True)
    duration = models.CharField(max_length=10, blank=False, unique=False)
    created_by = models.CharField(max_length=50, unique=True, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f'Course Name: {self.course_name}'


class Contact(models.Model):
    name = models.CharField(max_length=120, blank=False)
    email_address = models.EmailField()
    subject = models.CharField(max_length=128, blank=False, unique=False)
    message = models.CharField(max_length=500, blank=False)

    def __str__(self) -> str:
        return f'Contacted Person: {self.name}'

class Testimonial(models.Model):
    name = models.CharField(max_length=100, unique=True, blank=False)
    email = models.EmailField()
    text = models.CharField(max_length=1000, blank=False)

    def __str__(self) -> str:
        return f'Name: {self.name}'


class About(models.Model):
    title = models.CharField(max_length=255, blank=False)
    image_file = models.ImageField(upload_to='about_images')
    content = models.CharField(max_length=5000, blank=False, unique=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.title


class Mission(models.Model):
    title = models.CharField(max_length=255, blank=False)
    content = models.CharField(max_length=2000)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.title
    
class Partners(models.Model):
    partner_name = models.CharField(max_length=55, unique=True, blank=False)
    ABV = models.CharField(max_length=10, unique=True, blank=False)
    logo = models.ImageField(upload_to='partner images', blank=False)
    joined_at = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f'Name: {self.partner_name} Date Joined {self.joined_at} Created at: {self.created_at}'
    

main/forms.py
from django import forms
from .models import Contact, Testimonial

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

        widget = {
            
        }
    

class TestimonialForm(forms.ModelForm):
    class Meta:
        model = Testimonial
        fields = '__all__'

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from .models import *
from .forms import *

def home_view(request):
    courses = Courses.objects.all()

    if courses.exists():
        course_detail = Courses.first()
    else:
        course_detail = None

    context = {
        'courses': courses,
        'course_detail': course_detail
    }
    return render(request, 'main/index.html', context)

def contact_view(request):
    if request.method == 'POST':
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            contact_form.save(commit=False)
            messages.success(request, 'Your message has been sent successfully!')

            return redirect('contact')
        else:
            messages.error(request, 'There was an error with your submission. Please try again.')
    else:
        contact_form = ContactForm()

    return render(request, 'main/contact.html', {'form': contact_form})            

def about_view(request):
    
    return render(request, 'main/about.html')

def coures_view(request):
    courses = Courses.objects.all()

    return render(request, 'main/course.html', {'courses': courses})

def course_detail_view(request, course_id):
    course_detail = get_object_or_404(Courses, id = course_id)

    return render(request, 'main/course_detail.html', {'course_detail': course_detail})

main/templates/main/about.html
{% extends 'main/base.html' %}
{% block title %}About{% endblock %}
{% load static %}
{% block content %}

    <!-- Header Start -->
    <div class="container-fluid page-header" style="margin-bottom: 90px;">
        <div class="container">
            <div class="d-flex flex-column justify-content-center" style="min-height: 300px">
                <h3 class="display-4 text-white text-uppercase">About</h3>
                <div class="d-inline-flex text-white">
                    <p class="m-0 text-uppercase"><a class="text-white" href="">Home</a></p>
                    <i class="fa fa-angle-double-right pt-1 px-3"></i>
                    <p class="m-0 text-uppercase">About</p>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->

    <!-- About Start -->
    <div class="container-fluid py-5">
        <div class="container py-5">
            <div class="row align-items-center">
                <div class="col-lg-5">
                    <img class="img-fluid rounded mb-4 mb-lg-0" src="{% static 'images/main/about.jpg' %}" alt="">
                </div>
                <div class="col-lg-7">
                    <div class="text-left mb-4">
                        <h5 class="text-primary text-uppercase mb-3" style="letter-spacing: 5px;">About Us</h5>
                        <h1>Innovative Way To Learn</h1>
                    </div>
                    <p>Aliquyam accusam clita nonumy ipsum sit sea clita ipsum clita, ipsum dolores amet voluptua duo dolores et sit ipsum rebum, sadipscing et erat eirmod diam kasd labore clita est. Diam sanctus gubergren sit rebum clita amet, sea est sea vero sed et. Sadipscing labore tempor at sit dolor clita consetetur diam. Diam ut diam tempor no et, lorem dolore invidunt no nonumy stet ea labore, dolor justo et sit gubergren diam sed sed no ipsum. Sit tempor ut nonumy elitr dolores justo aliquyam ipsum stet</p>
                    <a href="" class="btn btn-primary py-md-2 px-md-4 font-weight-semi-bold mt-2">Learn More</a>
                </div>
            </div>
        </div>
    </div>
    <!-- About End -->

{% endblock %}

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="{% static 'images/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet"> 

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
    <!-- Topbar Start -->
    <div class="container-fluid d-lg-block top-bar">
        <div class="row align-items-center">
            <div class="col-lg-4 text-center">
                <div class="d-inline-flex align-items-center">
                    <i class="fa fa-map-marker-alt text-primary mr-3"></i>
                    <div class="text-left">
                        <h6 class="">Our Office</h6>
                        <small>123 Street, New York, USA</small>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 text-center">
                <div class="d-inline-flex align-items-center">
                    <i class="fa fa-envelope text-primary mr-3"></i>
                    <div class="text-left">
                        <h6 class="">Email Us</h6>
                        <small>info@example.com</small>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 text-center">
                <div class="d-inline-flex align-items-center">
                    <i class="fa fa-phone text-primary mr-3"></i>
                    <div class="text-left">
                        <h6 class="">Call Us</h6>
                        <small>+012 345 6789</small>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Top Bar End -->

<!-- Top Navbar Start -->
<div class="container-fluid top-navbar">
    <div class="row border-top px-xl-5">
        <!-- Main Navbar -->
        <div class="col-lg-9">
            <nav class="navbar navbar-expand-lg navbar-light bg-light py-3 px-0">
                <a class="navbar-brand d-none d-lg-block" href="#">
                    <img class="logo-image" src="{% static 'images/logo/logo.png' %}" alt="Logo" style="height: 50px;">
                </a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-center" id="navbarCollapse">
                    {% if user.is_authenticated %}
                        <!-- If the student is logged in, show profile and logout options -->
                        <div class="navbar-nav py-0">
                            <a href="{% url 'main:home' %}" class="nav-item nav-link active">All Course</a>
                            <a href="{% url 'main:course' %}" class="nav-item nav-link"></a>
                            <a href="{% url 'main:about' %}" class="nav-item nav-link"></a>
                            <a href="#" class="nav-item nav-link">Mission</a>
                            <a href="{% url 'main:contact' %}" class="nav-item nav-link"></a>
                        </div>
                        <div class="btn-group ml-lg-3 d-none d-lg-block">
                            <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{ user.email }}
                            </button>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="{% url 'account:profile' %}">Profile</a>
                                <a class="dropdown-item" href="{% url 'student:view_courses' %}">View Courses</a>
                                <a class="dropdown-item" href="{% url 'student:view_certificate' %}">Certificates</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'account:logout' %}">Logout</a>
                            </div>
                        </div>
                    {% else %}
                        <!-- If no user is logged in, show login/register button -->
                        <div class="navbar-nav py-0">
                            <a href="{% url 'main:home' %}" class="nav-item nav-link active">Home</a>
                            <a href="{% url 'main:course' %}" class="nav-item nav-link">Courses</a>
                            <a href="{% url 'main:about' %}" class="nav-item nav-link">About</a>
                            <a href="#" class="nav-item nav-link">Mission</a>
                            <a href="{% url 'main:contact' %}" class="nav-item nav-link">Contact</a>
                        </div>
                        <a class="btn btn-primary py-2 px-4 ml-lg-3 d-none d-lg-block" href="{% url 'student:home' %}">Login | Register</a>
                    {% endif %}
                </div>
            </nav>
        </div>
    </div>
</div>
<!-- Top Navbar End -->

    <div>
        {% block content %}
        {% endblock %}
    </div>

    <!-- Footer Start -->
    <footer class="footer">
        <div class="container-fluid bg-dark text-white py-5 px-sm-3 px-lg-5" style="margin-top: 90px;">
            <div class="row pt-5">
                <div class="col-lg-7 col-md-12">
                    <div class="row">
                        <div class="col-md-6 mb-5">
                            <h5 class="text-primary text-uppercase mb-4" style="letter-spacing: 5px;">Get In Touch</h5>
                            <p><i class="fa fa-map-marker-alt mr-2"></i>123 Street, New York, USA</p>
                            <p><i class="fa fa-phone-alt mr-2"></i>+012 345 67890</p>
                            <p><i class="fa fa-envelope mr-2"></i>info@example.com</p>
                            <div class="d-flex justify-content-start mt-4">
                                <a class="btn btn-outline-light btn-square mr-2" href="#"><i class="fab fa-twitter"></i></a>
                                <a class="btn btn-outline-light btn-square mr-2" href="#"><i class="fab fa-facebook-f"></i></a>
                                <a class="btn btn-outline-light btn-square mr-2" href="#"><i class="fab fa-linkedin-in"></i></a>
                                <a class="btn btn-outline-light btn-square" href="#"><i class="fab fa-instagram"></i></a>
                            </div>
                        </div>
                        <div class="col-md-6 mb-5">
                            <h5 class="text-primary text-uppercase mb-4" style="letter-spacing: 5px;">Our Courses</h5>
                            <div class="d-flex flex-column justify-content-start">
                                <a class="text-white mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Web Design</a>
                                <a class="text-white mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Apps Design</a>
                                <a class="text-white mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Marketing</a>
                                <a class="text-white mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Research</a>
                                <a class="text-white" href="#"><i class="fa fa-angle-right mr-2"></i>SEO</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-5 col-md-12 mb-5">
                    <h5 class="text-primary text-uppercase mb-4" style="letter-spacing: 5px;">Newsletter</h5>
                    <p>Rebum labore lorem dolores kasd est, et ipsum amet et at kasd, ipsum sea tempor magna tempor. Accu kasd sed ea duo ipsum. Dolor duo eirmod sea justo no lorem est diam</p>
                    <div class="w-100">
                        <div class="input-group">
                            <input type="text" class="form-control border-light" style="padding: 30px;" placeholder="Your Email Address">
                            <div class="input-group-append">
                                <button class="btn btn-primary px-4">Sign Up</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container-fluid bg-dark text-white border-top py-4 px-sm-3 px-md-5" style="border-color: rgba(256, 256, 256, .1) !important;">
            <div class="row">
                <div class="col-lg-6 text-center text-md-left mb-3 mb-md-0">
                    <p class="m-0 text-white">&copy; <a href="#">Domain Name</a>. All Rights Reserved. Designed by <a href="https://htmlcodex.com">HTML Codex</a>
                    </p>
                </div>
                <div class="col-lg-6 text-center text-md-right">
                    <ul class="nav d-inline-flex">
                        <li class="nav-item">
                            <a class="nav-link text-white py-0" href="#">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white py-0" href="#">Terms</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white py-0" href="#">FAQs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white py-0" href="#">Help</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer End -->

    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="fa fa-angle-double-up"></i></a>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <!-- <script src="{ static 'lib/easing/easing.min.js' %}"></script>
    <script src="{ static 'lib/owlcarousel/owl.carousel.min.js' %}"></script> -->

    <!-- Contact Javascript File -->
    <!-- <script src="{ static 'mail/jqBootstrapValidation.min.js' %}"></script>
    <script src="{ static 'mail/contact.js' %}"></script> -->

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

main/templates/main/contact.html
{% extends 'main/base.html' %}
{% block title %}Contact{% endblock %}
{% load static %}
{% block content %}

    <!-- Header Start -->
    <div class="container-fluid page-header" style="margin-bottom: 90px;">
        <div class="container">
            <div class="d-flex flex-column justify-content-center" style="min-height: 300px">
                <h3 class="display-4 text-white text-uppercase">Contact</h3>
                <div class="d-inline-flex text-white">
                    <p class="m-0 text-uppercase"><a class="text-white" href="">Home</a></p>
                    <i class="fa fa-angle-double-right pt-1 px-3"></i>
                    <p class="m-0 text-uppercase">Contact</p>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->

    <!-- Contact Start -->
    <div class="container-fluid py-5">
        <div class="container py-5">
            <div class="text-center mb-5">
                <h5 class="text-primary text-uppercase mb-3" style="letter-spacing: 5px;">Contact</h5>
                <h1>Contact For Any Query</h1>
            </div>
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <div class="contact-form bg-secondary rounded p-5">
                        <div id="success"></div>
                        <form name="sentMessage" id="contactForm" novalidate="novalidate">
                            <div class="control-group">
                                <input type="text" class="form-control border-0 p-4" id="name" placeholder="Your Name" required="required" data-validation-required-message="Please enter your name" />
                                <p class="help-block text-danger"></p>
                            </div>
                            <div class="control-group">
                                <input type="email" class="form-control border-0 p-4" id="email" placeholder="Your Email" required="required" data-validation-required-message="Please enter your email" />
                                <p class="help-block text-danger"></p>
                            </div>
                            <div class="control-group">
                                <input type="text" class="form-control border-0 p-4" id="subject" placeholder="Subject" required="required" data-validation-required-message="Please enter a subject" />
                                <p class="help-block text-danger"></p>
                            </div>
                            <div class="control-group">
                                <textarea class="form-control border-0 py-3 px-4" rows="5" id="message" placeholder="Message" required="required" data-validation-required-message="Please enter your message"></textarea>
                                <p class="help-block text-danger"></p>
                            </div>
                            <div class="text-center">
                                <button class="btn btn-primary py-3 px-5" type="submit" id="sendMessageButton">Send Message</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Contact End -->

{% endblock %}

main/templates/main/course.html
{% extends 'main/base.html' %}
{% block title %}Courses{% endblock %}
{% load static %}
{% block content %}

    <!-- Header Start -->
    <div class="container-fluid page-header" style="margin-bottom: 90px;">
        <div class="container">
            <div class="d-flex flex-column justify-content-center" style="min-height: 300px">
                <h3 class="display-4 text-white text-uppercase">Courses</h3>
                <div class="d-inline-flex text-white">
                    <p class="m-0 text-uppercase"><a class="text-white" href="">Home</a></p>
                    <i class="fa fa-angle-double-right pt-1 px-3"></i>
                    <p class="m-0 text-uppercase">Courses</p>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->

    <!-- Courses Start -->
    <div class="container-fluid py-5">
        <div class="container py-5">
            <div class="text-center mb-5">
                <h5 class="text-primary text-uppercase mb-3" style="letter-spacing: 5px;">Courses</h5>
                <h1>Our Popular Courses</h1>
            </div>
            <div class="row">
                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="rounded overflow-hidden mb-2">
                        <img class="img-fluid" src="{% static 'images/main/course-1.jpg' %}" alt="">
                        <div class="bg-secondary p-4">
                            <div class="d-flex justify-content-between mb-3">
                                <small class="m-0"><i class="fa fa-users text-primary mr-2"></i>25 Students</small>
                                <small class="m-0"><i class="far fa-clock text-primary mr-2"></i>01h 30m</small>
                            </div>
                            <a class="h5" href="">Web design & development courses for beginner</a>
                            <div class="border-top mt-4 pt-4">
                                <div class="d-flex justify-content-between">
                                    <h6 class="m-0"><i class="fa fa-star text-primary mr-2"></i>4.5 <small>(250)</small></h6>
                                    <h5 class="m-0">$99</h5>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="rounded overflow-hidden mb-2">
                        <img class="img-fluid" src="{% static 'images/main/course-2.jpg' %}" alt="">
                        <div class="bg-secondary p-4">
                            <div class="d-flex justify-content-between mb-3">
                                <small class="m-0"><i class="fa fa-users text-primary mr-2"></i>25 Students</small>
                                <small class="m-0"><i class="far fa-clock text-primary mr-2"></i>01h 30m</small>
                            </div>
                            <a class="h5" href="">Web design & development courses for beginner</a>
                            <div class="border-top mt-4 pt-4">
                                <div class="d-flex justify-content-between">
                                    <h6 class="m-0"><i class="fa fa-star text-primary mr-2"></i>4.5 <small>(250)</small></h6>
                                    <h5 class="m-0">$99</h5>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="rounded overflow-hidden mb-2">
                        <img class="img-fluid" src="{% static 'images/main/course-3.jpg' %}" alt="">
                        <div class="bg-secondary p-4">
                            <div class="d-flex justify-content-between mb-3">
                                <small class="m-0"><i class="fa fa-users text-primary mr-2"></i>25 Students</small>
                                <small class="m-0"><i class="far fa-clock text-primary mr-2"></i>01h 30m</small>
                            </div>
                            <a class="h5" href="">Web design & development courses for beginner</a>
                            <div class="border-top mt-4 pt-4">
                                <div class="d-flex justify-content-between">
                                    <h6 class="m-0"><i class="fa fa-star text-primary mr-2"></i>4.5 <small>(250)</small></h6>
                                    <h5 class="m-0">$99</h5>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        </div>
    </div>
    <!-- Courses End -->

{% endblock %}